//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROMPERU.PeruInfo.WEB {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROMPERU.PeruInfo.WEB.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso de Privacidad.
        /// </summary>
        public static string aviso_privacidad {
            get {
                return ResourceManager.GetString("aviso_privacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blog Perú.
        /// </summary>
        public static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string boton_aceptar_cookies {
            get {
                return ResourceManager.GetString("boton_aceptar_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string boton_cerrar_cookies {
            get {
                return ResourceManager.GetString("boton_cerrar_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar otra consulta.
        /// </summary>
        public static string boton_confirmacion_consulta {
            get {
                return ResourceManager.GetString("boton_confirmacion_consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver más noticias.
        /// </summary>
        public static string boton_ver_mas_noticias {
            get {
                return ResourceManager.GetString("boton_ver_mas_noticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver noticia.
        /// </summary>
        public static string boton_ver_noticias {
            get {
                return ResourceManager.GetString("boton_ver_noticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a noticias.
        /// </summary>
        public static string boton_volver_a_noticias {
            get {
                return ResourceManager.GetString("boton_volver_a_noticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string btn_enviar {
            get {
                return ResourceManager.GetString("btn_enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busca por categoría, subcategoría o término específicor.
        /// </summary>
        public static string buscar_alt {
            get {
                return ResourceManager.GetString("buscar_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros de búsqueda.
        /// </summary>
        public static string buscar_filtros {
            get {
                return ResourceManager.GetString("buscar_filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda por país.
        /// </summary>
        public static string buscar_pais {
            get {
                return ResourceManager.GetString("buscar_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado para.
        /// </summary>
        public static string buscar_para {
            get {
                return ResourceManager.GetString("buscar_para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busca por nombre.
        /// </summary>
        public static string buscar_por_nombre {
            get {
                return ResourceManager.GetString("buscar_por_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentra lo que buscas.
        /// </summary>
        public static string buscar_texto {
            get {
                return ResourceManager.GetString("buscar_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa la palabra clave.
        /// </summary>
        public static string buscar_texto_alt {
            get {
                return ResourceManager.GetString("buscar_texto_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo requerido.
        /// </summary>
        public static string campo_requerido {
            get {
                return ResourceManager.GetString("campo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CATEGORÍAS.
        /// </summary>
        public static string categorias {
            get {
                return ResourceManager.GetString("categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si tienes alguna duda escríbenos a.
        /// </summary>
        public static string consulta_subtitulo_1 {
            get {
                return ResourceManager.GetString("consulta_subtitulo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a o llena el siguiente formulario.
        /// </summary>
        public static string consulta_subtitulo_2 {
            get {
                return ResourceManager.GetString("consulta_subtitulo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Déjanos tu consulta.
        /// </summary>
        public static string consulta_titulo {
            get {
                return ResourceManager.GetString("consulta_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;Al parecer esta página no se encuentra disponible.&lt;br&gt;&lt;br&gt;Te invitamos a visitar otros contenidos de nuestra web.&lt;/p&gt;.
        /// </summary>
        public static string contenido_error {
            get {
                return ResourceManager.GetString("contenido_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descubra más.
        /// </summary>
        public static string cookies_descubra_mas {
            get {
                return ResourceManager.GetString("cookies_descubra_mas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descubre más.
        /// </summary>
        public static string descubre_mas {
            get {
                return ResourceManager.GetString("descubre_mas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de publicación.
        /// </summary>
        public static string fecha_publicacion {
            get {
                return ResourceManager.GetString("fecha_publicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtra tu búsqueda.
        /// </summary>
        public static string filtrar_busqueda {
            get {
                return ResourceManager.GetString("filtrar_busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las categorías.
        /// </summary>
        public static string filtrar_busqueda_todos {
            get {
                return ResourceManager.GetString("filtrar_busqueda_todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        public static string label_desde {
            get {
                return ResourceManager.GetString("label_desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        public static string label_hasta {
            get {
                return ResourceManager.GetString("label_hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al hacer clic en enviar estás aceptando nuestros.
        /// </summary>
        public static string lbl_terminos {
            get {
                return ResourceManager.GetString("lbl_terminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar fechas.
        /// </summary>
        public static string limpiar_fechas {
            get {
                return ResourceManager.GetString("limpiar_fechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicita el uso de la marca Perú  y marcas sectoriales.
        /// </summary>
        public static string link_licenciatarios_texto {
            get {
                return ResourceManager.GetString("link_licenciatarios_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://peru.info/es-pe/licenciatarios.
        /// </summary>
        public static string link_licenciatarios_url {
            get {
                return ResourceManager.GetString("link_licenciatarios_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a noticias.
        /// </summary>
        public static string link_noticias {
            get {
                return ResourceManager.GetString("link_noticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticias.
        /// </summary>
        public static string noticias {
            get {
                return ResourceManager.GetString("noticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados para:.
        /// </summary>
        public static string resultados_para {
            get {
                return ResourceManager.GetString("resultados_para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conoce y descarga nuestras apps oficiales desde el App Store o Play Store de tu celular: PISCO SPIRIT OF PERU, PERÚ BROCHURE, HABLA QUECHUA y más..
        /// </summary>
        public static string seo_descripcion_apps {
            get {
                return ResourceManager.GetString("seo_descripcion_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conoce a los peruanos que contribuyeron a posicionar la Marca Perú entre las más reconocidas del mundo..
        /// </summary>
        public static string seo_descripcion_campana {
            get {
                return ResourceManager.GetString("seo_descripcion_campana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentra información relevante, tendencias del sector salud sobre la coyuntura actual del Perú y el mundo..
        /// </summary>
        public static string seo_descripcion_comunicado {
            get {
                return ResourceManager.GetString("seo_descripcion_comunicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si tienes alguna duda escríbenos a inversiones@promperu.gob.pe o envíanos tus datos en el siguiente formulario..
        /// </summary>
        public static string seo_descripcion_contacto {
            get {
                return ResourceManager.GetString("seo_descripcion_contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últimas noticias e información oficial de Perú como MARCA PAÍS. Conoce más sobre: Turismo, Gastronomía, Comercio Exterior, Inversiones y Talento del Perú..
        /// </summary>
        public static string seo_descripcion_home {
            get {
                return ResourceManager.GetString("seo_descripcion_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conoce los reconocimientos internacionales de la Marca Perú en Turismo, Gastronomía, Imagen Corporativa, Marketing Promocional y más..
        /// </summary>
        public static string seo_descripcion_premios {
            get {
                return ResourceManager.GetString("seo_descripcion_premios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El aviso de privacidad describe las prácticas para el manejo de información personal que usa Perú Info..
        /// </summary>
        public static string seo_descripcion_privacidad {
            get {
                return ResourceManager.GetString("seo_descripcion_privacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La comida peruana se ha posicionado como una de las mejores gastronomías del mundo. Conoce los restaurantes peruanos más destacados en el exterior..
        /// </summary>
        public static string seo_descripcion_restaurante {
            get {
                return ResourceManager.GetString("seo_descripcion_restaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conoce las obligaciones y responsabilidades legales de uso del sitio Web de Perú Info..
        /// </summary>
        public static string seo_descripcion_terminos {
            get {
                return ResourceManager.GetString("seo_descripcion_terminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apps, Aplicaciones Móviles, Play Store, App Store.
        /// </summary>
        public static string seo_keywords_apps {
            get {
                return ResourceManager.GetString("seo_keywords_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Embajadores, Marca Perú, Marca País.
        /// </summary>
        public static string seo_keywords_campana {
            get {
                return ResourceManager.GetString("seo_keywords_campana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COVID, Salud, Coronavirus, Pandemia.
        /// </summary>
        public static string seo_keywords_comunicado {
            get {
                return ResourceManager.GetString("seo_keywords_comunicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportaciones Peruanas, Inversiones Extranjeras, Inversiones en el Perú.
        /// </summary>
        public static string seo_keywords_contacto {
            get {
                return ResourceManager.GetString("seo_keywords_contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca Perú, Marca País, PROMPERÚ, Turismo, Gastronomía, Importacion y Exportacion.
        /// </summary>
        public static string seo_keywords_home {
            get {
                return ResourceManager.GetString("seo_keywords_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca Perú, Marca País, Turismo, Gastronomía, Imagen Corporativa, Marketing Promocional.
        /// </summary>
        public static string seo_keywords_premios {
            get {
                return ResourceManager.GetString("seo_keywords_premios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso de Privacidad, Información Personal, Datos Personales.
        /// </summary>
        public static string seo_keywords_privacidad {
            get {
                return ResourceManager.GetString("seo_keywords_privacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastronomía Peruana, Comida Peruana, Restaurantes Peruanos.
        /// </summary>
        public static string seo_keywords_restaurante {
            get {
                return ResourceManager.GetString("seo_keywords_restaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ley aplicable, Responsabilidades Legales, Propiedad Intelectual.
        /// </summary>
        public static string seo_keywords_terminos {
            get {
                return ResourceManager.GetString("seo_keywords.terminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestras Apps | Aplicaciones Móviles | Play Store | App Store | Perú Info.
        /// </summary>
        public static string seo_titulo_apps {
            get {
                return ResourceManager.GetString("seo_titulo_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campañas de la Marca Perú | Perú Info.
        /// </summary>
        public static string seo_titulo_campana {
            get {
                return ResourceManager.GetString("seo_titulo_campana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COVID 19 | Salud | Perú Info.
        /// </summary>
        public static string seo_titulo_comunicado {
            get {
                return ResourceManager.GetString("seo_titulo_comunicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto de Inversiones | Perú Info.
        /// </summary>
        public static string seo_titulo_contacto {
            get {
                return ResourceManager.GetString("seo_titulo_contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perú Info | Portal oficial de la Marca Perú.
        /// </summary>
        public static string seo_titulo_home {
            get {
                return ResourceManager.GetString("seo_titulo_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Premios  &amp; Honores | Marca Perú | Perú Info.
        /// </summary>
        public static string seo_titulo_premios {
            get {
                return ResourceManager.GetString("seo_titulo_premios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso de privacidad | Perú Info.
        /// </summary>
        public static string seo_titulo_privacidad {
            get {
                return ResourceManager.GetString("seo_titulo_privacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurantes de Cocina Peruana en el Mundo | Perú Info.
        /// </summary>
        public static string seo_titulo_restaurante {
            get {
                return ResourceManager.GetString("seo_titulo_restaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Términos y condiciones | Perú Info.
        /// </summary>
        public static string seo_titulo_terminos {
            get {
                return ResourceManager.GetString("seo_titulo_terminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aviso-de-privacidad.
        /// </summary>
        public static string slug_aviso_privacidad {
            get {
                return ResourceManager.GetString("slug_aviso_privacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a terminos-y-condiciones.
        /// </summary>
        public static string slug_terminos_condiciones {
            get {
                return ResourceManager.GetString("slug_terminos_condiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Me gusta Perú.
        /// </summary>
        public static string sociales {
            get {
                return ResourceManager.GetString("sociales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Términos y condiciones.
        /// </summary>
        public static string terminos_condiciones {
            get {
                return ResourceManager.GetString("terminos_condiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        public static string texto_aplicar {
            get {
                return ResourceManager.GetString("texto_aplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te responderemos lo más pronto posible a través del correo.
        /// </summary>
        public static string texto_confirmacion_consulta {
            get {
                return ResourceManager.GetString("texto_confirmacion_consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este sitio usa cookies:.
        /// </summary>
        public static string texto_cookies {
            get {
                return ResourceManager.GetString("texto_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alertas.
        /// </summary>
        public static string titulo_alertas {
            get {
                return ResourceManager.GetString("titulo_alertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Tu consulta ha sido enviada!.
        /// </summary>
        public static string titulo_confirmacion_consulta {
            get {
                return ResourceManager.GetString("titulo_confirmacion_consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conoce los restaurantes peruanos en el Mundo.
        /// </summary>
        public static string titulo_conoce_restaurantes {
            get {
                return ResourceManager.GetString("titulo_conoce_restaurantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo más reciente.
        /// </summary>
        public static string titulo_lo_mas_reciente {
            get {
                return ResourceManager.GetString("titulo_lo_mas_reciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo más visto.
        /// </summary>
        public static string titulo_lo_mas_visto {
            get {
                return ResourceManager.GetString("titulo_lo_mas_visto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a También te podría interesar.
        /// </summary>
        public static string titulo_podria_interesarte {
            get {
                return ResourceManager.GetString("titulo_podria_interesarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string txt_correo {
            get {
                return ResourceManager.GetString("txt_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string txt_last_name {
            get {
                return ResourceManager.GetString("txt_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuéntanos, ¿Cuál es tu consulta?.
        /// </summary>
        public static string txt_mensaje {
            get {
                return ResourceManager.GetString("txt_mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string txt_nombres {
            get {
                return ResourceManager.GetString("txt_nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perú dedicado a la&lt;br /&gt;agroindustria.
        /// </summary>
        public static string txt_peru_agroindustria {
            get {
                return ResourceManager.GetString("txt_peru_agroindustria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perú dedicado a la &lt;br /&gt;gastronomía.
        /// </summary>
        public static string txt_peru_gastronomia {
            get {
                return ResourceManager.GetString("txt_peru_gastronomia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver más.
        /// </summary>
        public static string ver_mas {
            get {
                return ResourceManager.GetString("ver_mas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver menos.
        /// </summary>
        public static string ver_menos {
            get {
                return ResourceManager.GetString("ver_menos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al Inicio.
        /// </summary>
        public static string volver_al_inicio {
            get {
                return ResourceManager.GetString("volver_al_inicio", resourceCulture);
            }
        }
    }
}
